// Trachycarpus fortunei, Windmill Palm https://en.wikipedia.org/wiki/Trachycarpus_fortunei

export const palmData = [
  {
    id: "4a",
    palms: [],
    temp: "-30 to -25 °F ",
  },
  {
    id: "4b",
    palms: [],
    temp: "-25 to -20 °F ",
  },
  {
    id: "5a",
    palms: [],
    temp: "-20 to -15 °F ",
  },
  {
    id: "5b",
    palms: [],
    temp: "-15 to -10 °F ",
  },
  {
    id: "6a",
    palms: [],
    temp: "-10 to -5 °F ",
  },
  {
    id: "6b",
    palms: ["needle palm"],
    temp: "-5 to 0 °F ",
  },
  {
    id: "7a",
    palms: ["Trachycarpus fortunei", "sabal-minor", "pindo-palm"],
    temp: "0 to 5 °F ",
  },
  {
    id: "7b",
    palms: [
      "Trachycarpus fortunei",
      "sabal-minor",
      "sabal-palmetto",
      "pindo-palm",
      "sago-palm",
      "cabbage-palmetto",
    ],
    temp: "5 to 10 °F ",
  },
  {
    id: "8a",
    palms: [
      "Trachycarpus fortunei",
      "sabal-minor",
      "sabal-palmetto",
      "pindo-palm",
      "sago-palm",
      "cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",

      "Saw Palmetto",
    ],
    temp: "10 to 15 °F ",
  },
  {
    id: "8b",
    palms: [
      "Trachycarpus fortunei",
      "sabal-minor",
      "sabal-palmetto",
      "pindo-palm",
      "sago-palm",
      "cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm",
    ],
    temp: "15 to 20 °F ",
  },
  {
    id: "9a",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm-Syagrus",
    ],
    temp: "20 to 25 °F ",
  },
  {
    id: "9b",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Royal Palm - Roystonea Regia",
    ],
    temp: "25 to 30 °F ",
  },
  {
    id: "10a",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Royal Palm - Roystonea Regia",
      "Key Thatch Palm - Leucothrinax morrisii",
      "Foxtail Plam - Wodyetia bifurcata",
      "High Plateau Coconut Plam - Beccariophoenix alfredi",
      "Areca Palm - Dypsis lutescens",
      "Florida Thatch Palm - Thrinax radiata",
      "Foxtaill Palm - Wodyetia bifurcata",
    ],
    temp: "30 to 35 °F ",
  },

  {
    id: "10b",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Key Thatch Palm - Leucothrinax morrisii",
      "Royal Palm - Roystonea Regia",
      "Foxtail Plam - Wodyetia bifurcata",
      "High Plateau Coconut Plam - Beccariophoenix alfredi",
      "Bottle Palm - Hyophorbe lagenicaulis",
      "Dwarf Majesty Palm - Ravenea hildebrandtii",
      "Christmas Palm - Adonidia merrillii",
      "Areca Palm - Dypsis lutescens",
      "Coconut Palm - Cocos nucifera",
      "Flordia Silver - Coccothrinax argentata",
      "Florida Thatch Palm - Thrinax radiata",
      "Foxtaill Palm - Wodyetia bifurcata",
    ],
    temp: "35 to 40 °F ",
  },
  {
    id: "11a",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Key Thatch Palm - Leucothrinax morrisii",
      "Royal Palm - Roystonea Regia",
      "Foxtail Plam - Wodyetia bifurcata",
      "High Plateau Coconut Plam - Beccariophoenix alfredi",
      "Bottle Palm - Hyophorbe lagenicaulis",
      "Dwarf Majesty Palm - Ravenea hildebrandtii",
      "Christmas Palm - Adonidia merrillii",
      "Areca Palm - Dypsis lutescens",
      "Coconut Palm - Cocos nucifera",
      "Flordia Silver - Coccothrinax argentata",
      "Florida Thatch Palm - Thrinax radiata",
      "Foxtaill Palm - Wodyetia bifurcata",
    ],
    temp: "40 to 45 °F ",
  },
];
