// Trachycarpus fortunei, Windmill Palm https://en.wikipedia.org/wiki/Trachycarpus_fortunei

export const palmData = [
  {
    id: "4a",
    palms: [],
  },
  {
    id: "4b",
    palms: [],
  },
  {
    id: "5a",
    palms: [],
  },
  {
    id: "5b",
    palms: [],
  },
  {
    id: "6a",
    palms: [],
  },
  {
    id: "6b",
    palms: ["needle palm"],
  },
  {
    id: "7b",
    palms: [
      "Trachycarpus fortunei",
      "sabal-minor",
      "sabal-palmetto",
      "pindo-palm",
      "sago-palm",
      "cabbage-palmetto",
    ],
  },
  {
    id: "8a",
    palms: [
      "Trachycarpus fortunei",
      "sabal-minor",
      "sabal-palmetto",
      "pindo-palm",
      "sago-palm",
      "cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",

      "Saw Palmetto",
    ],
  },
  {
    id: "8b",
    palms: [
      "Trachycarpus fortunei",
      "sabal-minor",
      "sabal-palmetto",
      "pindo-palm",
      "sago-palm",
      "cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm",
    ],
  },
  {
    id: "9a",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm-Syagrus",
    ],
  },
  {
    id: "9b",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Royal Palm - Roystonea Regia",
    ],
  },
  {
    id: "10a",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Royal Palm - Roystonea Regia",
      "Key Thatch Palm - Leucothrinax morrisii",
      "Foxtail Plam - Wodyetia bifurcata",
      "High Plateau Coconut Plam - Beccariophoenix alfredi",
      "Areca Palm - Dypsis lutescens",
      "Florida Thatch Palm - Thrinax radiata",
      "Foxtaill Palm - Wodyetia bifurcata",
    ],
  },

  {
    id: "10b",
    palms: [
      "Windmill Palm-Trachycarpus fortunei",
      "Sabal-minor",
      "Palmetto-Sabal-palmetto",
      "Pindo-palm",
      "Sago-palm",
      "Cabbage-palmetto",
      "Blue Hesper Palm",
      "Mediterranian Fan Palm",
      "Chilean Wine Palm",
      "Chinese Fan Palm",
      "Canary Island Date Palm",
      "Saw Palmetto",
      "California Fan Palm - Washingtonian Robusta",
      "Bismark Palm",
      "Queen Palm - Syagrus",
      "Key Thatch Palm - Leucothrinax morrisii",
      "Royal Palm - Roystonea Regia",
      "Foxtail Plam - Wodyetia bifurcata",
      "High Plateau Coconut Plam - Beccariophoenix alfredi",
      "Bottle Palm - Hyophorbe lagenicaulis",
      "Dwarf Majesty Palm - Ravenea hildebrandtii",
      "Christmas Palm - Adonidia merrillii",
      "Areca Palm - Dypsis lutescens",
      "Coconut Palm - Cocos nucifera",
      "Flordia Silver - Coccothrinax argentata",
      "Florida Thatch Palm - Thrinax radiata",
      "Foxtaill Palm - Wodyetia bifurcata",
    ],
  },
];
